### PR TITLE
fix add a project

### LINKED ISSUE #80: fix add a project

### PR DESCRIPTION
**Pull request by zakaria6907**
- fix add a project 
- add a column is_followed 
- add a method to hide projects that don't follow 
- don't forget symfony console d:m:m

### CODE REVIEW

**Review by AxelR972 — DISMISSED** [review]

File: src/Entity/Project.php [hunk 1]
```diff
@@ -67,6 +68,7 @@ public function setGithubLink(string $githubLink): self
     {
         $this->githubLink = $githubLink;
 
+        $this->fullName = substr($githubLink, strrpos($githubLink, '.com/') + 5);
```
Comment (aldaitzwild) [inline src/Entity/Project.php]: Not the right place to call this

**Review by aldaitzwild — CHANGES_REQUESTED** [review]

**Review by AxelR972 — DISMISSED** [review]

**Review by AxelR972 — APPROVED** [review]

**Review by aldaitzwild — APPROVED** [review]
